#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 16, 2018 04:01:23 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Add_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    Add_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    Add_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family mincho -size 17 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("264x226+428+161")
        top.title("New Toplevel")



        self.Add = Button(top)
        self.Add.place(relx=0.42, rely=0.49, height=36, width=37)
        self.Add.configure(activebackground="#d9d9d9")
        self.Add.configure(font=font10)
        self.Add.configure(text='''+''')

        self.Entry_1 = Entry(top)
        self.Entry_1.place(relx=0.08, rely=0.18,height=47, relwidth=0.36)
        self.Entry_1.configure(background="white")
        self.Entry_1.configure(font="TkFixedFont")
        self.Entry_1.configure(width=96)

        self.Entry_2 = Entry(top)
        self.Entry_2.place(relx=0.53, rely=0.18,height=47, relwidth=0.36)
        self.Entry_2.configure(background="white")
        self.Entry_2.configure(font="TkFixedFont")
        self.Entry_2.configure(selectbackground="#c4c4c4")

        self.disp_result = Entry(top)
        self.disp_result.place(relx=0.3, rely=0.71,height=47, relwidth=0.36)
        self.disp_result.configure(background="white")
        self.disp_result.configure(font="TkFixedFont")
        self.disp_result.configure(selectbackground="#c4c4c4")






if __name__ == '__main__':
    vp_start_gui()



