#!/usr/bin/env python3

import time
import multiprocessing

def calc_square(numbers):
    for n in numbers:
        time.sleep(5)
        print('square ' + str(n**2))

def calc_cube(numbers):
    for n in numbers:
        time.sleep(5)
        print('cube ' + str(n**3))

if __name__=='__main__':
    
    arr = [2, 3, 8, 9]

    t = time.time()
    
    p1 = multiprocessing.Process(target=calc_square, args=(arr,))
    p2 = multiprocessing.Process(target=calc_cube, args=(arr,))

    p1.start()
    p2.start()

    # now wait till other process is done
    p1.join()
    p2.join()

    print(time.time() - t)

    print('done')
